backend:
  name: git-gateway
  branch: master
media_folder: "uploads"
collections:
  - name: "course" # Used in routes, e.g., /admin/collections/blog
    label: "Curso" # Used in the UI
    folder: "src/p/course" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "perfil-curso.njk" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "course" }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Fecha de inicio", name: "start_date", widget: "datetime" }
      - { label: "Imagen del curso", name: "thumbnail", widget: "image" }
      - { label: "Imagen del slider", name: "thumbnails", widget: "image" }
      - { label: "Descripcion", name: "body", widget: "markdown" }
      - { label: "Url del Curso", name: "urlinscribete", widget: "string" }
  - name: "class" # Used in routes, e.g., /admin/collections/blog
    label: "Clase" # Used in the UI
    folder: "src/p/class" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "clase.njk" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "class" }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - label: "Curso"
        name: "course"
        widget: "relation"
        collection: "course"
        search_fields: ["title"]
        value_field: "title"
        display_fields: ["title"]
    sortable_fields: ['course','title']